server:
    port: 80
   
    servlet:
        context-path: /
        session:
              timeout: 6000
              redis:
                   flush-mode: on-save
                   namespace: spring:session:sessions
              
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        
        
logging:
  level: debug
  level.com.framework: debug
  path: logs/
  file: admin.log
  
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.example.hejing2.vo
    check-config-location: true
    executor-type: simple
    db-column-underline: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    
    
    configuration:
          map-underscore-to-camel-case: true
    global-config:
          #驼峰下划线转换
          db-column-underline: true
    db-config:
          db-type: mysql
           #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          id-type: 3
          logic-delete-value: 1
          logic-not-delete-value: 0
spring:
     session:
          store-type: redis
     redis:
          cluster:
                nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
                expireSeconds: 1200
                commandTimeout: 10000
       # 环境 dev|test|prod
     profiles:
          active: db
        
     
      